### ISSUE TITLE
something about feature

### ISSUE THREAD

**Issue by ZigHello** [UNICT-Fake-Audio/ASVspoof2019-feature-webview#1]
Hi,I noticed that the features in this project are presented in the form of images, and I was wondering if it would be convenient to provide a detailed process of feature extraction to data visualization.

**Comment by Helias** [comment]
Hi, we extracted the feature using the following libraries:
- **pydub** (specifically mediainfo from pydub.utils), through pydub has been extracted the bitrate
- **spafe** ([extract_feats / spfeats](https://spafe.readthedocs.io/en/latest/features/spfeats.html) )

We created a CSV file with all the features extracted, for the data visualization **matplotlib** has been used to graph the data.

I would like to release the code but for now, we are planning to do a huge refactoring.

**Comment by ZigHello** [comment]
Thank you very much for your answer.

**Comment by Helias** [comment]
if you don't need anything else, feel free to close this issue

**Comment by Helias** [comment]
@ZigHello here you can see in details how you can extract from one sample the features that we used https://github.com/UNICT-Fake-Audio/fake-audio-detector/blob/main/shared/feature_extraction.py
